global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "hono"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
    scrape_interval: 5s
  - job_name: "otel"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:9464"]
    scrape_interval: 5s
